version: "3.11"

services:
  anubis-eye:
    container_name: anubis_eye_v6
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python start_all.py
    restart: always
